---
title: "chlorophyll"
author: "Abraham Kanz"
date: "June 18, 2019"
output: word_document
---

```{r}
chlorophyll_measures$units<-chlorophyll_measures$chl*120
chlorophyll_measures$units_per_tot_area<-chlorophyll_measures$units/chlorophyll_measures$total_area
```

```{r}
chlorophyll_rock_measures<- chlorophyll_measures %>%
  separate(tank, c("tank", "type"), sep="-") %>%
  subset(type=="r")
  
view(chlorophyll_rock_measures)
```

```{r}
chlorophyll_rock_measures_merge<-merge(chlorophyll_rock_measures,trt_tanks)
chlorophyll_rock_measures_merge<-chlorophyll_rock_measures_merge[-c(13,57),]
chlorophyll_rock_measures_merge$date <- as.factor(chlorophyll_rock_measures_merge$date)
```


```{r}
get_prior(units_per_tot_area~date*trt+(1+date*trt|tank),data=chlorophyll_rock_measures_merge, family=Gamma(link="log"))

chloro_glm <-  brm(units_per_tot_area~date*trt+(1|tank),data=chlorophyll_rock_measures_merge, family=Gamma(link="log"),chains=4,
                  prior = c(prior(normal(0,4),class="Intercept"),
                             prior(normal(0,2),class="b")))

plot(marginal_effects(chloro_glm), points=T)
```



```{r}
marg_chloro_r_prior_mod <-marginal_effects(chloro_glm,method="fitted",effects="date:trt")

marg_chloro_r_prior_post <- fitted(chloro_glm, newdata=marg_chloro_r_prior_mod$`date:trt`,summary=F)

 

columns_chloro_r <- paste(marg_chloro_r_prior_mod$`date:trt`$date,"_",marg_chloro_r_prior_mod$`date:trt`$trt)

 

colnames(marg_chloro_r_prior_post) <- columns_chloro_r

marg_chloro_r_prior_post <- as.data.frame(marg_chloro_r_prior_post)

marg_chloro_r_prior_post$iter <- 1:nrow(marg_chloro_r_prior_post)

 

marg_chloro_r_prior_plot <- gather(marg_chloro_r_prior_post, trt, chloro,-iter)

 

marg_chloro_r_prior_plot2 <- marg_chloro_r_prior_plot %>%

  separate(trt, c("date","trt"), sep=' _ ')
```


#moved to chloro_stats
```{r}
#chloro_post_gg<-ggplot(data=marg_chloro_r_prior_plot2,aes(x=date,fill=trt,y=chloro))+
#  geom_boxplot(outlier.color = NA)+
#  scale_y_continuous(limits=c(0,3000))+
#  labs(x="Date",y=expression(mu*"g of chlorophyll "* alpha *"/"*cm^2))+
#  theme(axis.title = element_text(size=30),
#        text = element_text(size=25))+
#  geom_jitter(data=chlorophyll_rock_measures_merge,aes(x=date,y=units_per_tot_area, col=trt),width=0, #height = 0)+
#  labs(fill="Treatment",col="Treatment")
```

```{r}
ggsave(chloro_post_gg, file="chloro_post_gg.jpg", dpi=600, width=12, height=5, units="in")
```


```{r}
marg_chloro_r_prior_plot2%>%
  subset(trt=="cc")%>%
  
```



```{r}
chlorophyll_col_measures<- chlorophyll_measures %>%
  separate(tank, c("tank", "type"), sep="-") %>%
  subset(type=="c")

chlorophyll_col_measures$date <- as.factor(chlorophyll_col_measures$date)

chlorophyll_col_merge <- merge(chlorophyll_col_measures, trt_tanks)
```


```{r}
get_prior(chl~date*trt+(1+date*trt|tank),data=chlorophyll_col_merge, family=Gamma(link="log"))

chloro_col_glm <- brm(chl~date*trt+(1+date*trt|tank),data=chlorophyll_col_merge, family=Gamma(link="log"),chains=4,
                  prior = c(prior(normal(0,4),class="Intercept"),
                             prior(normal(0,2),class="b")))

marginal_effects(chloro_col_glm)
```

```{r}
marg_chloro_prior_mod <-marginal_effects(chloro_col_glm,method="fitted",effects="date:trt")

marg_chloro_prior_post <- fitted(chloro_col_glm, newdata=marg_chloro_prior_mod$`date:trt`,summary=F)

 

columns_chloro <- paste(marg_chloro_prior_mod$`date:trt`$date,"_",marg_chloro_prior_mod$`date:trt`$trt)

 

colnames(marg_chloro_prior_post) <- columns_chloro

marg_chloro_prior_post <- as.data.frame(marg_chloro_prior_post)

marg_chloro_prior_post$iter <- 1:nrow(marg_chloro_prior_post)

 

marg_chloro_prior_plot <- gather(marg_chloro_prior_post, trt, chloro,-iter)

 

marg_chloro_prior_plot2 <- marg_chloro_prior_plot %>%

  separate(trt, c("date","trt"), sep=' _ ')
```

#moved to chloro_stats
```{r}
#chloro_col_post_gg<-ggplot(data=marg_chloro_prior_plot2, aes(x=date, fill=trt, y=chloro))+
#  geom_boxplot(outlier.color=NA)+
#  scale_y_continuous(limits=c(0,20))+
#  labs(x="Date",y=expression(mu*"g of chlorophyll "* alpha *"/L"))+
#  theme(axis.title = element_text(size=30),
#        text = element_text(size=25))+
#  geom_jitter(data=chlorophyll_col_merge,aes(x=date,y=chl, col= trt),width=0, height = 0)+
#  labs(fill="Treatment",col="Treatment")
```

```{r}
ggsave(chloro_col_post_gg, file="chloro_col_post_gg.jpg", dpi=600, width=12, height=5, units="in")
```


```{r}
chloro_post_gg
```

```{r}
chloro_col_post_gg
```























